name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pentol Ngapung</title>
  <style>
    body {
      margin: 0;
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #177013; */apa lo buka buka kontol*/
    }

    .pentol-container {
      position: relative;
      animation: float 3s infinite ease-in-out;
    }

    .pentol {
      width: 100px;
      height: 100px;
      background-image: url('https://media.istockphoto.com/id/1136788853/id/vektor/vektor-ikon-jari-tengah-garis-kerangka-art-middle-thumb-menghina-gerakan-emoji-clipart.jpg?s=2048x2048&w=is&k=20&c=pysDlkcSY6wP3ylC1ZgZpGK-vYd_250DtBLlfW-vJnY=');
      background-size: cover;
      border-radius: 50%;
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
    }

    @keyframes float {
      0% {
        transform: translateY(0);
      }
      10% {
        transform: translateY(-50px);
      }
      100% {
        transform: translateY(0);
      }
    }
  </style>
</head>
<body>

  <div class="pentol-container">
    <div class="pentol"></div>
  </div>

</body>
</html>
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
